### ISSUE TITLE
why do you use ZeroMQ

### ISSUE THREAD

**Issue by HoangNgo88** [bersler/OpenLogReplicator#38]
Hi, I am reading your project and I love this project
I have a question, why do you choose ZeroMQ in your project instead of others like RabbitMQ or Kafka, are there any special feature but others dont have it. Can you share me about it. I am wondering when I should choose ZeroMQ instead of others like RabbitMQ or Kafka

**Comment by bersler** [comment]
Hi @HoangNgo88,

Please note that all targets apart of Kafka and file writer are actually prototypes. Nobody uses them. It might be something else not, ZeroMQ. No difference.
Why is RabbitMQ not implemented yet? Because I could not find a partner who would like to use it in production and spend some effort to make this implementation robust.

At the beginning of the project there was some functionality to output directly to Redis. Nobody used it so I stopped maintaining it and removed from code. There is theoretically support for protobuf format instead of json. I am not actually testing it - didn't have time even to build a testing environment for it. Maybe it does not work at all - but since nobody complained so far - nobody would care anyway.

If you have a business case and would such solution would help your business run better - please contact me and I might help you. If you are just asking why not implement 100 cool features which might be used or not (but it would be cool to have them), I might not have the time and resources to please you. You might not be able to convince me to implement it.

Happy Spring Festival!

Regards,
Adam
